package com.wy.eschart.model.esinfos;

import com.wy.eschart.model.esinfos.EsinfosDO;
import com.wy.eschart.model.esinfos.EsinfosDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface EsinfosDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbggenerated Thu Mar 02 17:26:51 CST 2017
     */
    @SelectProvider(type=EsinfosDOSqlProvider.class, method="countByExample")
    int countByExample(EsinfosDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbggenerated Thu Mar 02 17:26:51 CST 2017
     */
    @DeleteProvider(type=EsinfosDOSqlProvider.class, method="deleteByExample")
    int deleteByExample(EsinfosDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbggenerated Thu Mar 02 17:26:51 CST 2017
     */
    @Delete({
        "delete from esinfos",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbggenerated Thu Mar 02 17:26:51 CST 2017
     */
    @Insert({
        "insert into esinfos (name, aggs, ",
        "query, esurl, ctime, ",
        "mtime)",
        "values (#{name,jdbcType=VARCHAR}, #{aggs,jdbcType=OTHER}, ",
        "#{query,jdbcType=VARCHAR}, #{esurl,jdbcType=VARCHAR}, #{ctime,jdbcType=TIMESTAMP}, ",
        "#{mtime,jdbcType=TIMESTAMP})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(EsinfosDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbggenerated Thu Mar 02 17:26:51 CST 2017
     */
    @InsertProvider(type=EsinfosDOSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insertSelective(EsinfosDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbggenerated Thu Mar 02 17:26:51 CST 2017
     */
    @SelectProvider(type=EsinfosDOSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="aggs", property="aggs", jdbcType=JdbcType.OTHER),
        @Result(column="query", property="query", jdbcType=JdbcType.VARCHAR),
        @Result(column="esurl", property="esurl", jdbcType=JdbcType.VARCHAR),
        @Result(column="ctime", property="ctime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="mtime", property="mtime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<EsinfosDO> selectByExampleWithRowbounds(EsinfosDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbggenerated Thu Mar 02 17:26:51 CST 2017
     */
    @SelectProvider(type=EsinfosDOSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="aggs", property="aggs", jdbcType=JdbcType.OTHER),
        @Result(column="query", property="query", jdbcType=JdbcType.VARCHAR),
        @Result(column="esurl", property="esurl", jdbcType=JdbcType.VARCHAR),
        @Result(column="ctime", property="ctime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="mtime", property="mtime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<EsinfosDO> selectByExample(EsinfosDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbggenerated Thu Mar 02 17:26:51 CST 2017
     */
    @Select({
        "select",
        "id, name, aggs, query, esurl, ctime, mtime",
        "from esinfos",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="aggs", property="aggs", jdbcType=JdbcType.OTHER),
        @Result(column="query", property="query", jdbcType=JdbcType.VARCHAR),
        @Result(column="esurl", property="esurl", jdbcType=JdbcType.VARCHAR),
        @Result(column="ctime", property="ctime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="mtime", property="mtime", jdbcType=JdbcType.TIMESTAMP)
    })
    EsinfosDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbggenerated Thu Mar 02 17:26:51 CST 2017
     */
    @UpdateProvider(type=EsinfosDOSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") EsinfosDO record, @Param("example") EsinfosDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbggenerated Thu Mar 02 17:26:51 CST 2017
     */
    @UpdateProvider(type=EsinfosDOSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") EsinfosDO record, @Param("example") EsinfosDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbggenerated Thu Mar 02 17:26:51 CST 2017
     */
    @UpdateProvider(type=EsinfosDOSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(EsinfosDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbggenerated Thu Mar 02 17:26:51 CST 2017
     */
    @Update({
        "update esinfos",
        "set name = #{name,jdbcType=VARCHAR},",
          "aggs = #{aggs,jdbcType=OTHER},",
          "query = #{query,jdbcType=VARCHAR},",
          "esurl = #{esurl,jdbcType=VARCHAR},",
          "ctime = #{ctime,jdbcType=TIMESTAMP},",
          "mtime = #{mtime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(EsinfosDO record);
}