package com.wy.eschart.model.esinfos;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EsinfosDOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table esinfos
     *
     * @mbg.generated Wed Mar 08 17:05:39 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table esinfos
     *
     * @mbg.generated Wed Mar 08 17:05:39 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table esinfos
     *
     * @mbg.generated Wed Mar 08 17:05:39 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbg.generated Wed Mar 08 17:05:39 CST 2017
     */
    public EsinfosDOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbg.generated Wed Mar 08 17:05:39 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbg.generated Wed Mar 08 17:05:39 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbg.generated Wed Mar 08 17:05:39 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbg.generated Wed Mar 08 17:05:39 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbg.generated Wed Mar 08 17:05:39 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbg.generated Wed Mar 08 17:05:39 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbg.generated Wed Mar 08 17:05:39 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbg.generated Wed Mar 08 17:05:39 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbg.generated Wed Mar 08 17:05:39 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbg.generated Wed Mar 08 17:05:39 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table esinfos
     *
     * @mbg.generated Wed Mar 08 17:05:39 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameidIsNull() {
            addCriterion("nameid is null");
            return (Criteria) this;
        }

        public Criteria andNameidIsNotNull() {
            addCriterion("nameid is not null");
            return (Criteria) this;
        }

        public Criteria andNameidEqualTo(Integer value) {
            addCriterion("nameid =", value, "nameid");
            return (Criteria) this;
        }

        public Criteria andNameidNotEqualTo(Integer value) {
            addCriterion("nameid <>", value, "nameid");
            return (Criteria) this;
        }

        public Criteria andNameidGreaterThan(Integer value) {
            addCriterion("nameid >", value, "nameid");
            return (Criteria) this;
        }

        public Criteria andNameidGreaterThanOrEqualTo(Integer value) {
            addCriterion("nameid >=", value, "nameid");
            return (Criteria) this;
        }

        public Criteria andNameidLessThan(Integer value) {
            addCriterion("nameid <", value, "nameid");
            return (Criteria) this;
        }

        public Criteria andNameidLessThanOrEqualTo(Integer value) {
            addCriterion("nameid <=", value, "nameid");
            return (Criteria) this;
        }

        public Criteria andNameidIn(List<Integer> values) {
            addCriterion("nameid in", values, "nameid");
            return (Criteria) this;
        }

        public Criteria andNameidNotIn(List<Integer> values) {
            addCriterion("nameid not in", values, "nameid");
            return (Criteria) this;
        }

        public Criteria andNameidBetween(Integer value1, Integer value2) {
            addCriterion("nameid between", value1, value2, "nameid");
            return (Criteria) this;
        }

        public Criteria andNameidNotBetween(Integer value1, Integer value2) {
            addCriterion("nameid not between", value1, value2, "nameid");
            return (Criteria) this;
        }

        public Criteria andAggsIsNull() {
            addCriterion("aggs is null");
            return (Criteria) this;
        }

        public Criteria andAggsIsNotNull() {
            addCriterion("aggs is not null");
            return (Criteria) this;
        }

        public Criteria andAggsEqualTo(Object value) {
            addCriterion("aggs =", value, "aggs");
            return (Criteria) this;
        }

        public Criteria andAggsNotEqualTo(Object value) {
            addCriterion("aggs <>", value, "aggs");
            return (Criteria) this;
        }

        public Criteria andAggsGreaterThan(Object value) {
            addCriterion("aggs >", value, "aggs");
            return (Criteria) this;
        }

        public Criteria andAggsGreaterThanOrEqualTo(Object value) {
            addCriterion("aggs >=", value, "aggs");
            return (Criteria) this;
        }

        public Criteria andAggsLessThan(Object value) {
            addCriterion("aggs <", value, "aggs");
            return (Criteria) this;
        }

        public Criteria andAggsLessThanOrEqualTo(Object value) {
            addCriterion("aggs <=", value, "aggs");
            return (Criteria) this;
        }

        public Criteria andAggsIn(List<Object> values) {
            addCriterion("aggs in", values, "aggs");
            return (Criteria) this;
        }

        public Criteria andAggsNotIn(List<Object> values) {
            addCriterion("aggs not in", values, "aggs");
            return (Criteria) this;
        }

        public Criteria andAggsBetween(Object value1, Object value2) {
            addCriterion("aggs between", value1, value2, "aggs");
            return (Criteria) this;
        }

        public Criteria andAggsNotBetween(Object value1, Object value2) {
            addCriterion("aggs not between", value1, value2, "aggs");
            return (Criteria) this;
        }

        public Criteria andQueryIsNull() {
            addCriterion("query is null");
            return (Criteria) this;
        }

        public Criteria andQueryIsNotNull() {
            addCriterion("query is not null");
            return (Criteria) this;
        }

        public Criteria andQueryEqualTo(String value) {
            addCriterion("query =", value, "query");
            return (Criteria) this;
        }

        public Criteria andQueryNotEqualTo(String value) {
            addCriterion("query <>", value, "query");
            return (Criteria) this;
        }

        public Criteria andQueryGreaterThan(String value) {
            addCriterion("query >", value, "query");
            return (Criteria) this;
        }

        public Criteria andQueryGreaterThanOrEqualTo(String value) {
            addCriterion("query >=", value, "query");
            return (Criteria) this;
        }

        public Criteria andQueryLessThan(String value) {
            addCriterion("query <", value, "query");
            return (Criteria) this;
        }

        public Criteria andQueryLessThanOrEqualTo(String value) {
            addCriterion("query <=", value, "query");
            return (Criteria) this;
        }

        public Criteria andQueryLike(String value) {
            addCriterion("query like", value, "query");
            return (Criteria) this;
        }

        public Criteria andQueryNotLike(String value) {
            addCriterion("query not like", value, "query");
            return (Criteria) this;
        }

        public Criteria andQueryIn(List<String> values) {
            addCriterion("query in", values, "query");
            return (Criteria) this;
        }

        public Criteria andQueryNotIn(List<String> values) {
            addCriterion("query not in", values, "query");
            return (Criteria) this;
        }

        public Criteria andQueryBetween(String value1, String value2) {
            addCriterion("query between", value1, value2, "query");
            return (Criteria) this;
        }

        public Criteria andQueryNotBetween(String value1, String value2) {
            addCriterion("query not between", value1, value2, "query");
            return (Criteria) this;
        }

        public Criteria andEsurlIsNull() {
            addCriterion("esurl is null");
            return (Criteria) this;
        }

        public Criteria andEsurlIsNotNull() {
            addCriterion("esurl is not null");
            return (Criteria) this;
        }

        public Criteria andEsurlEqualTo(String value) {
            addCriterion("esurl =", value, "esurl");
            return (Criteria) this;
        }

        public Criteria andEsurlNotEqualTo(String value) {
            addCriterion("esurl <>", value, "esurl");
            return (Criteria) this;
        }

        public Criteria andEsurlGreaterThan(String value) {
            addCriterion("esurl >", value, "esurl");
            return (Criteria) this;
        }

        public Criteria andEsurlGreaterThanOrEqualTo(String value) {
            addCriterion("esurl >=", value, "esurl");
            return (Criteria) this;
        }

        public Criteria andEsurlLessThan(String value) {
            addCriterion("esurl <", value, "esurl");
            return (Criteria) this;
        }

        public Criteria andEsurlLessThanOrEqualTo(String value) {
            addCriterion("esurl <=", value, "esurl");
            return (Criteria) this;
        }

        public Criteria andEsurlLike(String value) {
            addCriterion("esurl like", value, "esurl");
            return (Criteria) this;
        }

        public Criteria andEsurlNotLike(String value) {
            addCriterion("esurl not like", value, "esurl");
            return (Criteria) this;
        }

        public Criteria andEsurlIn(List<String> values) {
            addCriterion("esurl in", values, "esurl");
            return (Criteria) this;
        }

        public Criteria andEsurlNotIn(List<String> values) {
            addCriterion("esurl not in", values, "esurl");
            return (Criteria) this;
        }

        public Criteria andEsurlBetween(String value1, String value2) {
            addCriterion("esurl between", value1, value2, "esurl");
            return (Criteria) this;
        }

        public Criteria andEsurlNotBetween(String value1, String value2) {
            addCriterion("esurl not between", value1, value2, "esurl");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNull() {
            addCriterion("ctime is null");
            return (Criteria) this;
        }

        public Criteria andCtimeIsNotNull() {
            addCriterion("ctime is not null");
            return (Criteria) this;
        }

        public Criteria andCtimeEqualTo(Date value) {
            addCriterion("ctime =", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotEqualTo(Date value) {
            addCriterion("ctime <>", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThan(Date value) {
            addCriterion("ctime >", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ctime >=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThan(Date value) {
            addCriterion("ctime <", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeLessThanOrEqualTo(Date value) {
            addCriterion("ctime <=", value, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeIn(List<Date> values) {
            addCriterion("ctime in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotIn(List<Date> values) {
            addCriterion("ctime not in", values, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeBetween(Date value1, Date value2) {
            addCriterion("ctime between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andCtimeNotBetween(Date value1, Date value2) {
            addCriterion("ctime not between", value1, value2, "ctime");
            return (Criteria) this;
        }

        public Criteria andMtimeIsNull() {
            addCriterion("mtime is null");
            return (Criteria) this;
        }

        public Criteria andMtimeIsNotNull() {
            addCriterion("mtime is not null");
            return (Criteria) this;
        }

        public Criteria andMtimeEqualTo(Date value) {
            addCriterion("mtime =", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotEqualTo(Date value) {
            addCriterion("mtime <>", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeGreaterThan(Date value) {
            addCriterion("mtime >", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("mtime >=", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeLessThan(Date value) {
            addCriterion("mtime <", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeLessThanOrEqualTo(Date value) {
            addCriterion("mtime <=", value, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeIn(List<Date> values) {
            addCriterion("mtime in", values, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotIn(List<Date> values) {
            addCriterion("mtime not in", values, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeBetween(Date value1, Date value2) {
            addCriterion("mtime between", value1, value2, "mtime");
            return (Criteria) this;
        }

        public Criteria andMtimeNotBetween(Date value1, Date value2) {
            addCriterion("mtime not between", value1, value2, "mtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table esinfos
     *
     * @mbg.generated do_not_delete_during_merge Wed Mar 08 17:05:39 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table esinfos
     *
     * @mbg.generated Wed Mar 08 17:05:39 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}