package com.wy.eschart.model.esinfos;

import java.util.Date;

public class EsinfosDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column esinfos.id
     *
     * @mbg.generated Fri Mar 03 10:52:21 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column esinfos.name
     *
     * @mbg.generated Fri Mar 03 10:52:21 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column esinfos.aggs
     *
     * @mbg.generated Fri Mar 03 10:52:21 CST 2017
     */
    private Object aggs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column esinfos.query
     *
     * @mbg.generated Fri Mar 03 10:52:21 CST 2017
     */
    private String query;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column esinfos.esurl
     *
     * @mbg.generated Fri Mar 03 10:52:21 CST 2017
     */
    private String esurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column esinfos.ctime
     *
     * @mbg.generated Fri Mar 03 10:52:21 CST 2017
     */
    private Date ctime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column esinfos.mtime
     *
     * @mbg.generated Fri Mar 03 10:52:21 CST 2017
     */
    private Date mtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column esinfos.id
     *
     * @return the value of esinfos.id
     *
     * @mbg.generated Fri Mar 03 10:52:21 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column esinfos.id
     *
     * @param id the value for esinfos.id
     *
     * @mbg.generated Fri Mar 03 10:52:21 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column esinfos.name
     *
     * @return the value of esinfos.name
     *
     * @mbg.generated Fri Mar 03 10:52:21 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column esinfos.name
     *
     * @param name the value for esinfos.name
     *
     * @mbg.generated Fri Mar 03 10:52:21 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column esinfos.aggs
     *
     * @return the value of esinfos.aggs
     *
     * @mbg.generated Fri Mar 03 10:52:21 CST 2017
     */
    public Object getAggs() {
        return aggs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column esinfos.aggs
     *
     * @param aggs the value for esinfos.aggs
     *
     * @mbg.generated Fri Mar 03 10:52:21 CST 2017
     */
    public void setAggs(Object aggs) {
        this.aggs = aggs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column esinfos.query
     *
     * @return the value of esinfos.query
     *
     * @mbg.generated Fri Mar 03 10:52:21 CST 2017
     */
    public String getQuery() {
        return query;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column esinfos.query
     *
     * @param query the value for esinfos.query
     *
     * @mbg.generated Fri Mar 03 10:52:21 CST 2017
     */
    public void setQuery(String query) {
        this.query = query == null ? null : query.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column esinfos.esurl
     *
     * @return the value of esinfos.esurl
     *
     * @mbg.generated Fri Mar 03 10:52:21 CST 2017
     */
    public String getEsurl() {
        return esurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column esinfos.esurl
     *
     * @param esurl the value for esinfos.esurl
     *
     * @mbg.generated Fri Mar 03 10:52:21 CST 2017
     */
    public void setEsurl(String esurl) {
        this.esurl = esurl == null ? null : esurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column esinfos.ctime
     *
     * @return the value of esinfos.ctime
     *
     * @mbg.generated Fri Mar 03 10:52:21 CST 2017
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column esinfos.ctime
     *
     * @param ctime the value for esinfos.ctime
     *
     * @mbg.generated Fri Mar 03 10:52:21 CST 2017
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column esinfos.mtime
     *
     * @return the value of esinfos.mtime
     *
     * @mbg.generated Fri Mar 03 10:52:21 CST 2017
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column esinfos.mtime
     *
     * @param mtime the value for esinfos.mtime
     *
     * @mbg.generated Fri Mar 03 10:52:21 CST 2017
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }
}