package com.wy.eschart.model.esinfos;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.wy.eschart.model.esinfos.EsinfosDO;
import com.wy.eschart.model.esinfos.EsinfosDOExample.Criteria;
import com.wy.eschart.model.esinfos.EsinfosDOExample.Criterion;
import com.wy.eschart.model.esinfos.EsinfosDOExample;
import java.util.List;
import java.util.Map;

public class EsinfosDOSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbggenerated Wed Mar 01 10:56:27 CST 2017
     */
    public String countByExample(EsinfosDOExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("esinfos");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbggenerated Wed Mar 01 10:56:27 CST 2017
     */
    public String deleteByExample(EsinfosDOExample example) {
        BEGIN();
        DELETE_FROM("esinfos");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbggenerated Wed Mar 01 10:56:27 CST 2017
     */
    public String insertSelective(EsinfosDO record) {
        BEGIN();
        INSERT_INTO("esinfos");
        
        if (record.getAggs() != null) {
            VALUES("aggs", "#{aggs,jdbcType=OTHER}");
        }
        
        if (record.getQuery() != null) {
            VALUES("query", "#{query,jdbcType=VARCHAR}");
        }
        
        if (record.getEsurl() != null) {
            VALUES("esurl", "#{esurl,jdbcType=VARCHAR}");
        }
        
        if (record.getCtime() != null) {
            VALUES("ctime", "#{ctime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getMtime() != null) {
            VALUES("mtime", "#{mtime,jdbcType=TIMESTAMP}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbggenerated Wed Mar 01 10:56:27 CST 2017
     */
    public String selectByExample(EsinfosDOExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("id");
        } else {
            SELECT("id");
        }
        SELECT("aggs");
        SELECT("query");
        SELECT("esurl");
        SELECT("ctime");
        SELECT("mtime");
        FROM("esinfos");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbggenerated Wed Mar 01 10:56:27 CST 2017
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        EsinfosDO record = (EsinfosDO) parameter.get("record");
        EsinfosDOExample example = (EsinfosDOExample) parameter.get("example");
        
        BEGIN();
        UPDATE("esinfos");
        
        if (record.getId() != null) {
            SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getAggs() != null) {
            SET("aggs = #{record.aggs,jdbcType=OTHER}");
        }
        
        if (record.getQuery() != null) {
            SET("query = #{record.query,jdbcType=VARCHAR}");
        }
        
        if (record.getEsurl() != null) {
            SET("esurl = #{record.esurl,jdbcType=VARCHAR}");
        }
        
        if (record.getCtime() != null) {
            SET("ctime = #{record.ctime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getMtime() != null) {
            SET("mtime = #{record.mtime,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbggenerated Wed Mar 01 10:56:27 CST 2017
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("esinfos");
        
        SET("id = #{record.id,jdbcType=INTEGER}");
        SET("aggs = #{record.aggs,jdbcType=OTHER}");
        SET("query = #{record.query,jdbcType=VARCHAR}");
        SET("esurl = #{record.esurl,jdbcType=VARCHAR}");
        SET("ctime = #{record.ctime,jdbcType=TIMESTAMP}");
        SET("mtime = #{record.mtime,jdbcType=TIMESTAMP}");
        
        EsinfosDOExample example = (EsinfosDOExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbggenerated Wed Mar 01 10:56:27 CST 2017
     */
    public String updateByPrimaryKeySelective(EsinfosDO record) {
        BEGIN();
        UPDATE("esinfos");
        
        if (record.getAggs() != null) {
            SET("aggs = #{aggs,jdbcType=OTHER}");
        }
        
        if (record.getQuery() != null) {
            SET("query = #{query,jdbcType=VARCHAR}");
        }
        
        if (record.getEsurl() != null) {
            SET("esurl = #{esurl,jdbcType=VARCHAR}");
        }
        
        if (record.getCtime() != null) {
            SET("ctime = #{ctime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getMtime() != null) {
            SET("mtime = #{mtime,jdbcType=TIMESTAMP}");
        }
        
        WHERE("id = #{id,jdbcType=INTEGER}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbggenerated Wed Mar 01 10:56:27 CST 2017
     */
    protected void applyWhere(EsinfosDOExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}