package com.wy.eschart.model;

import com.wy.eschart.model.chartInfos.ChartInfosDO;
import com.wy.eschart.model.chartInfos.ChartInfosDOExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface ChartInfosDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chartinfos
     *
     * @mbg.generated Wed Mar 08 17:05:39 CST 2017
     */
    @SelectProvider(type=ChartInfosDOSqlProvider.class, method="countByExample")
    long countByExample(ChartInfosDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chartinfos
     *
     * @mbg.generated Wed Mar 08 17:05:39 CST 2017
     */
    @DeleteProvider(type=ChartInfosDOSqlProvider.class, method="deleteByExample")
    int deleteByExample(ChartInfosDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chartinfos
     *
     * @mbg.generated Wed Mar 08 17:05:39 CST 2017
     */
    @Delete({
        "delete from chartinfos",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chartinfos
     *
     * @mbg.generated Wed Mar 08 17:05:39 CST 2017
     */
    @Insert({
        "insert into chartinfos (name, dslaggs, ",
        "comment)",
        "values (#{name,jdbcType=VARCHAR}, #{dslaggs,jdbcType=OTHER}, ",
        "#{comment,jdbcType=VARCHAR})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(ChartInfosDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chartinfos
     *
     * @mbg.generated Wed Mar 08 17:05:39 CST 2017
     */
    @InsertProvider(type=ChartInfosDOSqlProvider.class, method="insertSelective")
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insertSelective(ChartInfosDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chartinfos
     *
     * @mbg.generated Wed Mar 08 17:05:39 CST 2017
     */
    @SelectProvider(type=ChartInfosDOSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="dslaggs", property="dslaggs", jdbcType=JdbcType.OTHER),
        @Result(column="comment", property="comment", jdbcType=JdbcType.VARCHAR)
    })
    List<ChartInfosDO> selectByExampleWithRowbounds(ChartInfosDOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chartinfos
     *
     * @mbg.generated Wed Mar 08 17:05:39 CST 2017
     */
    @SelectProvider(type=ChartInfosDOSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="dslaggs", property="dslaggs", jdbcType=JdbcType.OTHER),
        @Result(column="comment", property="comment", jdbcType=JdbcType.VARCHAR)
    })
    List<ChartInfosDO> selectByExample(ChartInfosDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chartinfos
     *
     * @mbg.generated Wed Mar 08 17:05:39 CST 2017
     */
    @Select({
        "select",
        "id, name, dslaggs, comment",
        "from chartinfos",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="dslaggs", property="dslaggs", jdbcType=JdbcType.OTHER),
        @Result(column="comment", property="comment", jdbcType=JdbcType.VARCHAR)
    })
    ChartInfosDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chartinfos
     *
     * @mbg.generated Wed Mar 08 17:05:39 CST 2017
     */
    @UpdateProvider(type=ChartInfosDOSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ChartInfosDO record, @Param("example") ChartInfosDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chartinfos
     *
     * @mbg.generated Wed Mar 08 17:05:39 CST 2017
     */
    @UpdateProvider(type=ChartInfosDOSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ChartInfosDO record, @Param("example") ChartInfosDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chartinfos
     *
     * @mbg.generated Wed Mar 08 17:05:39 CST 2017
     */
    @UpdateProvider(type=ChartInfosDOSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ChartInfosDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chartinfos
     *
     * @mbg.generated Wed Mar 08 17:05:39 CST 2017
     */
    @Update({
        "update chartinfos",
        "set name = #{name,jdbcType=VARCHAR},",
          "dslaggs = #{dslaggs,jdbcType=OTHER},",
          "comment = #{comment,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ChartInfosDO record);
}