package com.wy.eschart.model;

import com.wy.eschart.model.esinfos.EsinfosDO;
import com.wy.eschart.model.esinfos.EsinfosDOExample.Criteria;
import com.wy.eschart.model.esinfos.EsinfosDOExample.Criterion;
import com.wy.eschart.model.esinfos.EsinfosDOExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class EsinfosDOSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbg.generated Fri Mar 03 10:52:21 CST 2017
     */
    public String countByExample(EsinfosDOExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("esinfos");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbg.generated Fri Mar 03 10:52:21 CST 2017
     */
    public String deleteByExample(EsinfosDOExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("esinfos");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbg.generated Fri Mar 03 10:52:21 CST 2017
     */
    public String insertSelective(EsinfosDO record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("esinfos");
        
        if (record.getName() != null) {
            sql.VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        
        if (record.getAggs() != null) {
            sql.VALUES("aggs", "#{aggs,jdbcType=OTHER}");
        }
        
        if (record.getQuery() != null) {
            sql.VALUES("query", "#{query,jdbcType=VARCHAR}");
        }
        
        if (record.getEsurl() != null) {
            sql.VALUES("esurl", "#{esurl,jdbcType=VARCHAR}");
        }
        
        if (record.getCtime() != null) {
            sql.VALUES("ctime", "#{ctime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getMtime() != null) {
            sql.VALUES("mtime", "#{mtime,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbg.generated Fri Mar 03 10:52:21 CST 2017
     */
    public String selectByExample(EsinfosDOExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("name");
        sql.SELECT("aggs");
        sql.SELECT("query");
        sql.SELECT("esurl");
        sql.SELECT("ctime");
        sql.SELECT("mtime");
        sql.FROM("esinfos");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbg.generated Fri Mar 03 10:52:21 CST 2017
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        EsinfosDO record = (EsinfosDO) parameter.get("record");
        EsinfosDOExample example = (EsinfosDOExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("esinfos");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getName() != null) {
            sql.SET("name = #{record.name,jdbcType=VARCHAR}");
        }
        
        if (record.getAggs() != null) {
            sql.SET("aggs = #{record.aggs,jdbcType=OTHER}");
        }
        
        if (record.getQuery() != null) {
            sql.SET("query = #{record.query,jdbcType=VARCHAR}");
        }
        
        if (record.getEsurl() != null) {
            sql.SET("esurl = #{record.esurl,jdbcType=VARCHAR}");
        }
        
        if (record.getCtime() != null) {
            sql.SET("ctime = #{record.ctime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getMtime() != null) {
            sql.SET("mtime = #{record.mtime,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbg.generated Fri Mar 03 10:52:21 CST 2017
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("esinfos");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("name = #{record.name,jdbcType=VARCHAR}");
        sql.SET("aggs = #{record.aggs,jdbcType=OTHER}");
        sql.SET("query = #{record.query,jdbcType=VARCHAR}");
        sql.SET("esurl = #{record.esurl,jdbcType=VARCHAR}");
        sql.SET("ctime = #{record.ctime,jdbcType=TIMESTAMP}");
        sql.SET("mtime = #{record.mtime,jdbcType=TIMESTAMP}");
        
        EsinfosDOExample example = (EsinfosDOExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbg.generated Fri Mar 03 10:52:21 CST 2017
     */
    public String updateByPrimaryKeySelective(EsinfosDO record) {
        SQL sql = new SQL();
        sql.UPDATE("esinfos");
        
        if (record.getName() != null) {
            sql.SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        if (record.getAggs() != null) {
            sql.SET("aggs = #{aggs,jdbcType=OTHER}");
        }
        
        if (record.getQuery() != null) {
            sql.SET("query = #{query,jdbcType=VARCHAR}");
        }
        
        if (record.getEsurl() != null) {
            sql.SET("esurl = #{esurl,jdbcType=VARCHAR}");
        }
        
        if (record.getCtime() != null) {
            sql.SET("ctime = #{ctime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getMtime() != null) {
            sql.SET("mtime = #{mtime,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table esinfos
     *
     * @mbg.generated Fri Mar 03 10:52:21 CST 2017
     */
    protected void applyWhere(SQL sql, EsinfosDOExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}