package com.wy.eschart.model.chartInfos;

public class ChartInfosDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chartinfos.id
     *
     * @mbg.generated Mon Mar 06 14:59:34 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chartinfos.name
     *
     * @mbg.generated Mon Mar 06 14:59:34 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chartinfos.comment
     *
     * @mbg.generated Mon Mar 06 14:59:34 CST 2017
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chartinfos.id
     *
     * @return the value of chartinfos.id
     *
     * @mbg.generated Mon Mar 06 14:59:34 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chartinfos.id
     *
     * @param id the value for chartinfos.id
     *
     * @mbg.generated Mon Mar 06 14:59:34 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chartinfos.name
     *
     * @return the value of chartinfos.name
     *
     * @mbg.generated Mon Mar 06 14:59:34 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chartinfos.name
     *
     * @param name the value for chartinfos.name
     *
     * @mbg.generated Mon Mar 06 14:59:34 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chartinfos.comment
     *
     * @return the value of chartinfos.comment
     *
     * @mbg.generated Mon Mar 06 14:59:34 CST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chartinfos.comment
     *
     * @param comment the value for chartinfos.comment
     *
     * @mbg.generated Mon Mar 06 14:59:34 CST 2017
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}